---
title: Инструкции пользователя X-Cart
description: Подробные инструкции про настройку X-Cart на русском языке
type: kb

# Paths
pages_path: _pages/kb_ru

# Urls
url: https://kb.x-cart.ru

# Search
search:
  preferred: kb.x-cart.ru

# Site settings
ga_code: UA-5826167-9
lang_default: ru