---
title: X-Cart 5 Developer Documentation
description: X-Cart 5 Developer Documentation
type: devs

# Paths
pages_path: _pages/devs_en

# Urls
url: https://devs.x-cart.com

# Search
search:
  preferred: devs.x-cart.com

# Site settings
lang_default: en
paginate_count: 5
paginate_path: "/what_is_new/page:num/"

# REST API
swagger_pages:
    latest_api: 5.3.3.3
    path: "/rest-api/v:version/"

swagger:
  - id: 5_3_3_0
    json: 'spec/5.3.3.0.json'
  - id: 5_3_3_3
    json: 'spec/5.3.3.3.json'